version: '3.8'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 5uDop94oomy&v(N
      POSTGRES_DB: kuky
      DB_PORT: 5429
      DB_HOST: localhost
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5428:5432"
    networks:
      - app-network
  
  node:
    build: .
    volumes:
      - .:/app
      - '/app/node_modules'
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - node
    networks:
      - app-network

certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - app-network
  
volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
